spring:
  cloud:
    loadbalancer:
      ribbon:
        enabled: true #Ribbon开关
  application:
    name: ribbon-consumer
server:
  port: 3001


eureka:
  instance:
    lease-renewal-interval-in-seconds: 30
  client:
    refresh:
      enable: false
    healthcheck:
      enabled: true #健康检查
    service-url:
      defaultZone: http://127.0.0.1:1111/eureka
      #defaultZone属性区分大小写，需要驼峰大小写，因为serviceUrl属性是Map<String, String>;
      # 因此，defaultZone属性并不遵循正常的Spring引导默认区域的蛇形惯例。
    register-with-eureka: true
    fetch-registry: true

management:
  endpoints:
    web:
      exposure:
        include: info,health,hystrix.stream   #Hystrix指标流